PATH_TO_DRIVER: '../conf/chromedriver.exe'
CAPTCHA_WAIT_TIME: 30

HUMBLE:
  URL: 'https://www.humblebundle.com'
  LOGIN_LOC: '/html/body/div/div/div[4]/nav[1]/div/span[1]'
  BODY_SEARCH: 'If this is you, please enter the following code into your browser:\\r\\n\\r\\n(?P<code>.+?)\\r\\n\\r\\n'

OUTLOOK:
  APPLICATION_NAME: 'Outlook.Application'
  NAMESPACE_NAME: 'MAPI'
  DEFAULT_FOLDER: 6
  SEARCH_DEPTH: 20
