PATH_TO_DRIVER: '../conf/chromedriver.exe'
humble:
  HUMBLE_LOGIN_LOC: '/html/body/div/div/div[4]/nav[1]/div/span[1]'
  HUMBLE_BODY_SEARCH: 'If this is you, please enter the following code into your browser:\\r\\n\\r\\n(?P<code>.+?)\\r\\n\\r\\n'
outlook:
  APPLICATION_NAME: 'Outlook.Application'
  NAMESPACE_NAME: 'MAPI'
  DEFAULT_FOLDER: 6
  SEARCH_DEPTH: 20
